name: Linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.15
      uses: actions/setup-node@v3
      with:
        node-version: 20.15
        cache: 'pnpm'
    
    - name: Install pnpm
      run: npm install -g pnpm
      
    - name: Install dependencies
      run: pnpm install
      
    - name: Install dependencies
      run: pnpm ci
    
    - name: Run linter
      run: |
        pnpm run lint
        pnpm run format