name: Super-Linter

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JS: true
          VALIDATE_TYPESCRIPT: true
          VALIDATE_JSON: true
          VALIDATE_ESLINT: true
          FILTER_REGEX_EXCLUDE: "(node_modules|\\.git|dist|docs|\\.env\\.js|\\.gitignore|pnpm-lock\\.yaml|README\\.md|\\.prettierrc\\.js)"
          ESLINT_FILE: .eslintrc.js

      - name: Upload Linter Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: super
